#!/bin/busybox sh
set -eu

export PATH="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin"

/bin/busybox --install -s
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mkdir -p /persistent /tmp /run
chmod 1777 /tmp
mount -t ext4 /dev/vda /persistent

if /usr/local/bin/test-zram-config.bash; then
    echo "TEST_PASS"
else
    status="$?"
    echo "TEST_FAIL ${status}"
fi

sync
poweroff -f
sleep 5
exit 1
