#!/bin/bash

trap '{ stty sane; printf "\n\nAborting\n\n"; exit 1; }' SIGINT SIGTERM

# Ensure root User
if [ $(id -u) -ne 0 ]; then
  echo ""
  echo "Must be run as root user: sudo $0"
  echo ""
  exit 1
fi

# Delete Profile Script
if [ -f /etc/profile.d/cvt2f2fs-ps.sh ]; then
  rm /etc/profile.d/cvt2f2fs-ps.sh
fi

# Check Init System
if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
  SYSTEMD=1
elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
  SYSTEMD=0
else
  echo ""
  echo "Unrecognized init system"
  echo ""
  exit 1
fi

# Get Root Partition
if [ ${SYSTEMD} -eq 1 ]; then
  ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
else
  if [ ! -h /dev/root ]; then
    echo ""
    echo "/dev/root does not exist or is not a symlink"
    echo ""
    exit 1
  fi
  ROOT_PART=$(readlink /dev/root)
fi

# Install realpath
realpath --version &> /dev/null
if [ $? -ne 0 ]; then
  apt-get -y install realpath
fi

# Get Program Path
PGMPATH=$(realpath $0)

echo ""
df
echo ""
sleep 3
echo ""
if [ "$1" = "" ]; then
  echo -n "Ok to convert SD card to F2FS (y/n)? "
  while read -r -n 1 -s answer; do
    if [[ "${answer}" = [yYnN] ]]; then
      echo "${answer}"
      if [[ "${answer}" = [yY] ]]; then
        break
      else
        echo ""
        echo "Aborted"
        echo ""
        exit 1
      fi
    fi
  done
  echo ""
  echo ""
  echo "Convert to F2FS: Phase 1"
  echo ""

  #
  if [ "${ROOT_PART}" = "mmcblk0p2" ]; then
    PARTUUID="$(sed -n 's|^.*root=\(\S\+\)\s.*|\1|p' /boot/cmdline.txt)"
    PARTUUID="${PARTUUID:0:(${#PARTUUID} - 1)}"
    sed -i 's|root=\S\+\s|root=/dev/mmcblk0p2 |' /boot/cmdline.txt
    sed -i "s|$PARTUUID|/dev/mmcblk0p|" /etc/fstab
  else
    echo ""
    echo "Not running from SD card: Can't convert to F2FS"
    echo ""
    exit 1
  fi

  # Update/Upgrade Raspbian
  echo ""
  echo "Updating/Upgrading Raspbian"
  if [ -e /etc/apt/listchanges.conf ]; then
    sed -i 's/frontend=pager/frontend=text/' /etc/apt/listchanges.conf
  fi
  apt-get -y update
  apt-get -y upgrade
  apt-get -y dist-upgrade
  if [ -e /etc/apt/listchanges.conf ]; then
    sed -i 's/frontend=text/frontend=pager/' /etc/apt/listchanges.conf
  fi


  # Create Profile Script
  cat <<EOF > /etc/profile.d/cvt2f2fs-ps.sh &&
#!/bin/bash

ps cax | grep cvt2f2fs-ps.sh > /dev/null
if [[ \$? -ne 0 && \$(id -u) -eq 0 ]]; then
  sudo ${PGMPATH} --phase2
fi
EOF

  # Reboot
  shutdown -r now
elif [ "$1" = "--phase2" ]; then
  echo "Convert to F2FS: Phase 2"
  echo ""
  echo ""

  # Install rsync
  rsync --version &> /dev/null
  if [ $? -ne 0 ]; then
    apt-get -y install rsync
  fi

  apt-get -y install f2fs-tools
  umount /dev/sda1 &> /dev/null
  umount /dev/sda2 &> /dev/null
  echo "Partitioning USB flash drive"
  fdisk /dev/sda <<EOF &> /dev/null
o
n
p
1


w
EOF
  partprobe
  echo "Creating ext4 filesystem on USB flash drive"
  mke2fs -F -q -t ext4 -L rootfs /dev/sda1 &> /dev/null
  echo "Copying root filesystem to USB flash drive (this will take a while)"
  mount /dev/sda1 /mnt
  rsync -ax / /mnt
  sed -i 's|/dev/mmcblk0p2|#/dev/mmcblk0p2|' /mnt/etc/fstab
  echo "/dev/sda1     /          ext4     defaults,noatime     0     1" >> /mnt/etc/fstab

  # Create Profile Script
  cat <<EOF > /mnt/etc/profile.d/cvt2f2fs-ps.sh &&
#!/bin/bash

ps cax | grep cvt2f2fs-ps.sh > /dev/null
if [[ \$? -ne 0 && \$(id -u) -eq 0 ]]; then
  sudo ${PGMPATH} --phase3
fi
EOF

  umount /mnt
  sed -i 's|root=/dev/mmcblk0p2|root=/dev/sda1|' /boot/cmdline.txt
  sed -i 's|rootwait|rootwait rootdelay=5|' /boot/cmdline.txt
  echo "Rebooting to USB flash drive"
  echo ""

  # Reboot
  shutdown -r now
elif [ "$1" = "--phase3" ]; then
  echo "Convert to F2FS: Phase 3"
  echo ""
  echo ""

  echo "Creating F2FS filesystem on SD card"
  wipefs --force -a /dev/mmcblk0p2 > /dev/null
  mkfs.f2fs /dev/mmcblk0p2 &> /dev/null
  echo "Copying root filesystem to SD card (this will take a while)"
  mount /dev/mmcblk0p2 /mnt
  rsync -ax / /mnt
  sed -i '/\/dev\/sda1/d' /mnt/etc/fstab
  sed -i 's|#/dev/mmcblk0p2|/dev/mmcblk0p2|' /mnt/etc/fstab
  sed -i 's|ext4|f2fs|' /mnt/etc/fstab
  sed -i 's|defaults,noatime|defaults,noatime,discard|' /mnt/etc/fstab

  # Create Profile Script
  cat <<EOF > /mnt/etc/profile.d/cvt2f2fs-ps.sh &&
#!/bin/bash

ps cax | grep cvt2f2fs-ps.sh > /dev/null
if [[ \$? -ne 0 && \$(id -u) -eq 0 ]]; then
  sudo ${PGMPATH} --phase4
fi
EOF

  umount /mnt
  sed -i 's|root=/dev/sda1|root=/dev/mmcblk0p2|' /boot/cmdline.txt
  sed -i 's|rootfstype=ext4|rootfstype=f2fs|' /boot/cmdline.txt
  sed -i 's|rootwait rootdelay=5|rootwait|' /boot/cmdline.txt
  echo "Rebooting to SD card"
  echo ""

  # Reboot
  shutdown -r now
elif [ "$1" = "--phase4" ]; then
  echo "Convert to F2FS: Phase 4"
  echo ""
  echo ""

  # Cleanup
  apt-get -y autoremove
  apt-get -y clean
  rm -r /boot.bak/ &> /dev/null

  echo ""
  echo "Convert to F2FS Complete"
  echo ""
fi
