name: ShellCheck

# Trigger the workflow on push or pull request
on:
  push:
    paths:
      - 'zram-config'
      - '**.bash'
      - '.github/workflows/shellcheck-action.yml'
  pull_request:
    paths:
      - 'zram-config'
      - '**.bash'
      - '.github/workflows/shellcheck-action.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Setup environment
         run: sudo -E bash -c set
       - name: "ShellCheck tests/*.bash"
         run: |
           echo "ShellCheck zram-config..."
           if shellcheck -x -s bash tests/*.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
         shell: bash
       - name: "ShellCheck install.bash"
         run: |
           echo "ShellCheck install.bash..."
           if shellcheck -x -s bash install.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
         shell: bash
       - name: "ShellCheck update.bash"
         run: |
           echo "ShellCheck update.bash..."
           if shellcheck -x -s bash update.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
         shell: bash
       - name: "ShellCheck uninstall.bash"
         run: |
           echo "ShellCheck uninstall.bash..."
           if shellcheck -x -s bash uninstall.bash; then echo "OK"; else echo "FAILED"; exit 1; fi
         shell: bash
       - name: "ShellCheck zram-config"
         run: |
           echo "ShellCheck zram-config..."
           if shellcheck -x -s bash zram-config; then echo "OK"; else echo "FAILED"; exit 1; fi
         shell: bash
