name: ShellCheck

# Trigger the workflow on push or pull request
on:
  push:
    paths:
      - 'zram-config'
      - '**.bash'
      - '.github/workflows/shellcheck-action.yml'
  pull_request:
    paths:
      - 'zram-config'
      - '**.bash'
      - '.github/workflows/shellcheck-action.yml'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
       - name: Checkout repository
         uses: actions/checkout@v5
       - name: "ShellCheck tests/*.bash"
         run: shellcheck -x -s bash tests/*.bash
       - name: "ShellCheck install.bash"
         run: shellcheck -x -s bash install.bash
       - name: "ShellCheck update.bash"
         run: shellcheck -x -s bash update.bash
       - name: "ShellCheck uninstall.bash"
         run: shellcheck -x -s bash uninstall.bash
       - name: "ShellCheck zram-config"
         run: shellcheck -x -s bash zram-config
